music:
  volume: 50
manager:
  users:
    add: []
    blacklist: []
    chat: [] 
    help: []
    id: []
    join: []
    leave: []
    pause: []
    play: []
    reset: []
    role: []
    show: []
    skip: []
    text_channel: []
    timeout: []
    user: []
    voice_channel: []
    volume: []
  roles:
    add: []
    blacklist: []
    chat: [] 
    help: []
    id: []
    join: []
    leave: []
    pause: []
    play: []
    reset: []
    role: []
    show: []
    skip: []
    text_channel: []
    timeout: []
    user: []
    voice_channel: []
    volume: []
  text_channels:
    add: []
    blacklist: []
    chat: [] 
    help: []
    id: []
    join: []
    leave: []
    pause: []
    play: []
    reset: []
    role: []
    show: []
    skip: []
    text_channel: []
    timeout: []
    user: []
    voice_channel: []
    volume: []
  voice_channels:
    add: []
    blacklist: []
    chat: [] 
    help: []
    id: []
    join: []
    leave: []
    pause: []
    play: []
    reset: []
    role: []
    show: []
    skip: []
    text_channel: []
    timeout: []
    user: []
    voice_channel: []
    volume: []
disconnect:
  timeout: 600
